### ISSUE TITLE
진행 사항

### ISSUE THREAD

**Issue by tjdvlf2880** [2023-GameProgramming/StreetView#1]
개발 로드맵 정리.

GoogleStreet API Doc : https://developers.google.com/maps/documentation/streetview/overview/

-완료 된 것-

API는 정적 사진만 제공하고 파노라마 이미지를 지원하지 않는다...
대신 파라미터를 주어 호출하면 특정 각도의 사진을 가져올 수 있다.

특정 위/경도 위치의 Street View 이미지를 상하좌우위아래 6장 가져와서 저장한다.
(호출 마다 돈이 빠짐으로 동적으로 계속 불러오기 보단, 그냥 저장해두는게 좋아 보인다) 

가져온 이미지로 SkyBox를 만들어 3d View를 구현한다.
마우스로 360도 화면을 제어한다.

-이제 해야 할 것-

StreetView img는 유저가 생성한 것과 공식 생성된 것이 있는데 구분 없이 얻어진다.
api는 img말고도 metadata를 받아 올 수 있다.(요건 공짜다)
meta data에서는  지정 반경 내 StreetView이미지 여부와 해당 이미지가 있는 장소의 위/경도 정보를 알 수 있다.

meta data를 통해 현재 주변 이동 가능 장소를 찾고 
그것을 화면에 띄워주고
키보드 조작을 통해 이동한다(순간이동)

**Comment by kimdoheon01** [comment]
플레이어가 이동할 때 맵도 이동하는 건 어려우니까 그럼 맵에서 특정 장소를 클릭하면 맵이 그 장소로 교체되는 그런 걸 넣어볼까요? 마침 마우스에 따라 카메라 시점도 바뀌는 걸 넣었으니 예로 건물을 클릭하면 해당 건물 내부로 들어가는 거죠
